import os

lines = []
lines.append("@IsTest")
lines.append("public with sharing class DonationTriggerHandlerTest {")
lines.append("")
lines.append("    @TestSetup")
lines.append("    static void setupData() {")
lines.append("        Programme__c prog = new Programme__c(")
lines.append("            Name                    = 'Rural Youth Skills - Limpopo',")
lines.append("            Status__c               = 'Active',")
lines.append("            Province__c             = 'Limpopo',")
lines.append("            Focus_Area__c           = 'Youth Skills Development',")
lines.append("            Target_Beneficiaries__c = 500,")
lines.append("            Funding_Goal__c         = 250000")
lines.append("        );")
lines.append("        insert prog;")
lines.append("        Contact donor = new Contact(")
lines.append("            FirstName = 'Sinothando',")
lines.append("            LastName  = 'Test Donor'")
lines.append("        );")
lines.append("        insert donor;")
lines.append("    }")
lines.append("")
lines.append("    @IsTest")
lines.append("    static void testTotalDonationsOnInsert() {")
lines.append("        Programme__c prog  = [SELECT Id FROM Programme__c LIMIT 1];")
lines.append("        Contact      donor = [SELECT Id FROM Contact LIMIT 1];")
lines.append("        List<Donation__c> donations = new List<Donation__c>();")
lines.append("        for (Integer i = 0; i < 5; i++) {")
lines.append("            donations.add(new Donation__c(")
lines.append("                Programme__c     = prog.Id,")
lines.append("                Donor__c         = donor.Id,")
lines.append("                Amount__c        = 1000,")
lines.append("                Donation_Date__c = Date.today()")
lines.append("            ));")
lines.append("        }")
lines.append("        Test.startTest();")
lines.append("        insert donations;")
lines.append("        Test.stopTest();")
lines.append("        Programme__c result = [SELECT Total_Donations__c FROM Programme__c WHERE Id = :prog.Id];")
lines.append("        System.assertEquals(5000, result.Total_Donations__c, 'Total should be R5000');")
lines.append("    }")
lines.append("")
lines.append("    @IsTest")
lines.append("    static void testTotalRecalculatedOnUpdate() {")
lines.append("        Programme__c prog  = [SELECT Id FROM Programme__c LIMIT 1];")
lines.append("        Contact      donor = [SELECT Id FROM Contact LIMIT 1];")
lines.append("        Donation__c donation = new Donation__c(")
lines.append("            Programme__c     = prog.Id,")
lines.append("            Donor__c         = donor.Id,")
lines.append("            Amount__c        = 2000,")
lines.append("            Donation_Date__c = Date.today()")
lines.append("        );")
lines.append("        insert donation;")
lines.append("        Test.startTest();")
lines.append("        donation.Amount__c = 5000;")
lines.append("        update donation;")
lines.append("        Test.stopTest();")
lines.append("        Programme__c result = [SELECT Total_Donations__c FROM Programme__c WHERE Id = :prog.Id];")
lines.append("        System.assertEquals(5000, result.Total_Donations__c, 'Total should be R5000 after update');")
lines.append("    }")
lines.append("")
lines.append("    @IsTest")
lines.append("    static void testTotalRecalculatedOnDelete() {")
lines.append("        Programme__c prog  = [SELECT Id FROM Programme__c LIMIT 1];")
lines.append("        Contact      donor = [SELECT Id FROM Contact LIMIT 1];")
lines.append("        Donation__c donation = new Donation__c(")
lines.append("            Programme__c     = prog.Id,")
lines.append("            Donor__c         = donor.Id,")
lines.append("            Amount__c        = 8000,")
lines.append("            Donation_Date__c = Date.today()")
lines.append("        );")
lines.append("        insert donation;")
lines.append("        Test.startTest();")
lines.append("        delete donation;")
lines.append("        Test.stopTest();")
lines.append("        Programme__c result = [SELECT Total_Donations__c FROM Programme__c WHERE Id = :prog.Id];")
lines.append("        System.assertEquals(0, result.Total_Donations__c, 'Total should be R0 after delete');")
lines.append("    }")
lines.append("")
lines.append("    @IsTest")
lines.append("    static void testHighValueDonorFlagged() {")
lines.append("        Programme__c prog  = [SELECT Id FROM Programme__c LIMIT 1];")
lines.append("        Contact      donor = [SELECT Id FROM Contact LIMIT 1];")
lines.append("        Donation__c bigDonation = new Donation__c(")
lines.append("            Programme__c     = prog.Id,")
lines.append("            Donor__c         = donor.Id,")
lines.append("            Amount__c        = 15000,")
lines.append("            Donation_Date__c = Date.today()")
lines.append("        );")
lines.append("        Test.startTest();")
lines.append("        insert bigDonation;")
lines.append("        Test.stopTest();")
lines.append("        Contact result = [SELECT Description FROM Contact WHERE Id = :donor.Id];")
lines.append("        System.assert(result.Description != null && result.Description.contains('High-Value Donor'), 'Should be flagged');")
lines.append("    }")
lines.append("")
lines.append("    @IsTest")
lines.append("    static void testBelowThresholdNotFlagged() {")
lines.append("        Programme__c prog  = [SELECT Id FROM Programme__c LIMIT 1];")
lines.append("        Contact      donor = [SELECT Id FROM Contact LIMIT 1];")
lines.append("        Donation__c smallDonation = new Donation__c(")
lines.append("            Programme__c     = prog.Id,")
lines.append("            Donor__c         = donor.Id,")
lines.append("            Amount__c        = 500,")
lines.append("            Donation_Date__c = Date.today()")
lines.append("        );")
lines.append("        Test.startTest();")
lines.append("        insert smallDonation;")
lines.append("        Test.stopTest();")
lines.append("        Contact result = [SELECT Description FROM Contact WHERE Id = :donor.Id];")
lines.append("        System.assert(result.Description == null || !result.Description.contains('High-Value Donor'), 'Should not be flagged');")
lines.append("    }")
lines.append("")
lines.append("    @IsTest")
lines.append("    static void testBulk200Donations() {")
lines.append("        Programme__c prog  = [SELECT Id FROM Programme__c LIMIT 1];")
lines.append("        Contact      donor = [SELECT Id FROM Contact LIMIT 1];")
lines.append("        List<Donation__c> bulk = new List<Donation__c>();")
lines.append("        for (Integer i = 0; i < 200; i++) {")
lines.append("            bulk.add(new Donation__c(")
lines.append("                Programme__c     = prog.Id,")
lines.append("                Donor__c         = donor.Id,")
lines.append("                Amount__c        = 100,")
lines.append("                Donation_Date__c = Date.today()")
lines.append("            ));")
lines.append("        }")
lines.append("        Test.startTest();")
lines.append("        insert bulk;")
lines.append("        Test.stopTest();")
lines.append("        Programme__c result = [SELECT Total_Donations__c FROM Programme__c WHERE Id = :prog.Id];")
lines.append("        System.assertEquals(20000, result.Total_Donations__c, 'Total should be R20000');")
lines.append("    }")
lines.append("")
lines.append("    @IsTest")
lines.append("    static void testFundingProgressFormula() {")
lines.append("        Programme__c prog  = [SELECT Id FROM Programme__c LIMIT 1];")
lines.append("        Contact      donor = [SELECT Id FROM Contact LIMIT 1];")
lines.append("        List<Donation__c> donations = new List<Donation__c>();")
lines.append("        for (Integer i = 0; i < 5; i++) {")
lines.append("            donations.add(new Donation__c(")
lines.append("                Programme__c     = prog.Id,")
lines.append("                Donor__c         = donor.Id,")
lines.append("                Amount__c        = 25000,")
lines.append("                Donation_Date__c = Date.today()")
lines.append("            ));")
lines.append("        }")
lines.append("        Test.startTest();")
lines.append("        insert donations;")
lines.append("        Test.stopTest();")
lines.append("        Programme__c result = [SELECT Total_Donations__c, Funding_Progress__c FROM Programme__c WHERE Id = :prog.Id];")
lines.append("        System.assertEquals(125000, result.Total_Donations__c, 'Total should be R125000');")
lines.append("        System.assertEquals(50, result.Funding_Progress__c, 'Progress should be 50 percent');")
lines.append("    }")
lines.append("}")

path = "force-app/main/default/classes/DonationTriggerHandlerTest.cls"
with open(path, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines))

with open(path, "rb") as f:
    content = f.read()

print(f"Written: {len(content)} bytes")
print(f"Lines: {len(lines)}")
print(f"Angle brackets intact: {'List<Donation__c>' in content.decode('utf-8')}")